services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: winestore-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: winestore
    ports:
      - "5432:5432"
    restart: unless-stopped
